### ISSUE TITLE
收货地址

### ISSUE THREAD

**Issue by Foundj** [tumobi/nideshop-mini-program#1]
发现下单后无法显示完全收货信息，另外这个可否改为获取默认微信的收货地址更方便?
非常感谢！是一个精致的学习 demo！

**Comment by tumobi** [comment]
订单和用户这一块，目前还没有完成，还在开发中。

**Comment by Foundj** [comment]
期待！可有一个时间进度安排？

**Comment by tumobi** [comment]
订单和会员这块，计划是这个月完成
