### ISSUE TITLE
小程序的购物车在ios下不能使用

### ISSUE THREAD

**Issue by TonyYinChina** [tumobi/nideshop-mini-program#13]
购物车功能在Android的机器上工作正常，
IOS设备在购物车没有确认菜单。
加不了物品。
如下图：
![_20180227122111](https://user-images.githubusercontent.com/22854388/36710526-8d7bac72-1bb9-11e8-8404-6bc26e71608d.jpg)

**Comment by angelfreedomv** [comment]
ios貌似需要https跨域请求吧

**Comment by TonyYinChina** [comment]
应不是
