### ISSUE TITLE
请问一下，我更具你简书的步骤打起服务器后访问错是什么问题，麻烦指导一下哦

### ISSUE THREAD

**Issue by gzjiangying** [tumobi/nideshop-mini-program#15]
![image](https://user-images.githubusercontent.com/15151438/37131728-c4d097c0-22c4-11e8-9dde-d89085b13205.png)

**Comment by tumobi** [comment]
这不是错误，这是api接口

**Comment by gzjiangying** [comment]
好的谢谢。
