### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by vanloc0301** [tumobi/nideshop-mini-program#3]
I run command: `npm start` at project: https://github.com/tumobi/nideshop

How to run front end project?

I tried `npm start` at nideshop-mini-program.

**Comment by mengmingtian** [comment]
https://mp.weixin.qq.com/debug/wxadoc/dev/

**Comment by Foundj** [comment]
nideshop-mini-program is weixin program 。https://mp.weixin.qq.com/debug/wxadoc/dev/index.html?t=2017621
