### ISSUE TITLE
后台管理

### ISSUE THREAD

**Issue by TuobayeJiang** [tumobi/nideshop-mini-program#36]
你好，后台管理系统计划什么时候能添加

**Comment by caizhengjun** [comment]
INSERT INTO `nideshop_channel` VALUES (1, '居家', '/pages/category/category?id=1005000', 'http://ac-3yr0g9cz.clouddn.com/c031ea3cf575f885cd1c.png', 1);
这个图片无法访问了，有最新的地址可以告知一下吗？
非常感谢！
