### ISSUE TITLE
地址编辑时的省市区列表无法滚动

### ISSUE THREAD

**Issue by KennyLeung** [tumobi/nideshop-mini-program#7]
新增或编辑地址时，省、市、区三级联动的列表无法往下滚动，导致选择不到下面的条目。

**Comment by hfstack** [comment]
addressAdd.wxss中的部分样式问题

.region-select .bd{
  height: 492rpx;
  width: 100%;
  padding: 0 30rpx;
  overflow: scroll;
}
.region-select .region-list{
  height: auto;
}
